### ISSUE TITLE
empty file: ertel_a_gardeniny_ikh_dvornya_priverzhenzy_i_vragi_1889.xml

### ISSUE THREAD

**Issue by DanilSko** [dachelnokova/russian-novels#1]
This file https://github.com/dachelnokova/russian-novels/blob/main/texts/ertel_a_gardeniny_ikh_dvornya_priverzhenzy_i_vragi_1889.xml is empty for some reason

**Comment by dachelnokova** [comment]
Fixed. Thanks!
